{
 "title": "Dynamo SCinet Challenge",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Number of Workflows",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event:\"stampede.xwf.start\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Number of Jobs",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event:\"stampede.inv.end\" AND inv_id: [0 TO *] AND exitcode:0",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Files Transferred",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "total_files",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event:\"transfer.inv.local.single\" AND (source_url:\"*casa-dtn*\" OR destination_url:\"*casa-dtn*\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Data Transferred",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "decmbytes",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "bytes_transferred",
       "id": "1",
       "inlineScript": "_value/1024/1024",
       "meta": {},
       "settings": { "script": { "inline": "_value/1024/1024" } },
       "type": "sum"
      }
     ],
     "query": "event:\"transfer.inv.local.single\" AND (source_url:\"*casa-dtn*\" OR destination_url:\"*casa-dtn*\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Data Transferred over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decmbytes", "label": "Data Transferred" }
   ],
   "targets": [
    {
     "alias": "Stage_IN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "bytes_transferred",
       "id": "1",
       "inlineScript": "_value/1024/1024",
       "meta": {},
       "settings": { "script": { "inline": "_value/1024/1024" } },
       "type": "sum"
      }
     ],
     "query": "event:\"transfer.inv.local.single\" AND source_url:\"*casa-dtn*\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Stage_OUT",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "bytes_transferred",
       "id": "1",
       "inlineScript": "_value/1024/1024",
       "meta": {},
       "settings": { "script": { "inline": "_value/1024/1024" } },
       "type": "sum"
      }
     ],
     "query": "event:\"transfer.inv.local.single\" AND destination_url:\"*casa-dtn*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Files Transferred over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Files Transferred" }
   ],
   "targets": [
    {
     "alias": "Stage_IN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "total_files",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event:\"transfer.inv.local.single\" AND source_url:\"*casa-dtn*\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Stage_OUT",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event:\"transfer.inv.local.single\" AND destination_url:\"*casa-dtn*\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}