{
 "title": "Dynamo Workflow View",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Number of Workflows Submitted",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event:\"stampede.xwf.start\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Hail Workflows Started",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event:\"stampede.xwf.start\" AND dag:*casa_hail_*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Wind Workflows Started",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event:\"stampede.xwf.start\" AND dag:*casa_wind_*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Cumulative Time",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "s",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "local_dur",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event:\"stampede.job_inst.main.end\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Number of Tasks Submitted",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event:\"stampede.inv.start\" AND inv_id: [0 TO *]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Number of Successful Tasks",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event:\"stampede.inv.end\" AND inv_id: [0 TO *] AND exitcode: 0",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Number of Failed Tasks",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event:\"stampede.inv.end\" AND inv_id: [0 TO *] AND (NOT exitcode: 0)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Number of Tasks Executed on ExoGENI",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event:\"stampede.job_inst.host.info\" AND hostname:*exogeni*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Number of Tasks Executed on Chameleon",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event:\"stampede.job_inst.host.info\" AND hostname:*chameleon*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Tasks Submitted over Time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Tasks" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event:\"stampede.inv.start\" AND inv_id: [0 TO *]",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}