{
 "title": "Dynamo Data View",
 "time": { "from": "2019-10-21T16:00:22.293Z", "to": "2019-10-21T18:00:55.450Z" },
 "panels": [
  {
   "title": "Total Files Transferred From/To the DTN",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "total_files",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event:\"transfer.inv.local.single\" AND (source_url:\"*casa-dtn*\" OR destination_url:\"*casa-dtn*\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Data Transferred From/To the DTN",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "decmbytes",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "bytes_transferred",
       "id": "1",
       "inlineScript": "_value/1024/1024",
       "meta": {},
       "settings": { "script": { "inline": "_value/1024/1024" } },
       "type": "sum"
      }
     ],
     "query": "event:\"transfer.inv.local.single\" AND (source_url:\"*casa-dtn*\" OR destination_url:\"*casa-dtn*\")",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Data Transferred To ExoGENI",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "decmbytes",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "bytes_transferred",
       "id": "1",
       "inlineScript": "_value/1024/1024",
       "meta": {},
       "settings": { "script": { "inline": "_value/1024/1024" } },
       "type": "sum"
      }
     ],
     "query": "event:\"transfer.inv.local.single\" AND source_url:\"*casa-dtn*\" AND hostname:\"*exogeni*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Data Transferred To Chameleon",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "decmbytes",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "bytes_transferred",
       "id": "1",
       "inlineScript": "_value/1024/1024",
       "meta": {},
       "settings": { "script": { "inline": "_value/1024/1024" } },
       "type": "sum"
      }
     ],
     "query": "event:\"transfer.inv.local.single\" AND source_url:\"*casa-dtn*\" AND hostname:\"*chameleon*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Data Transferred over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decmbytes", "label": "Data Transferred" }
   ],
   "targets": [
    {
     "alias": "Stage_IN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "bytes_transferred",
       "id": "1",
       "inlineScript": "_value/1024/1024",
       "meta": {},
       "settings": { "script": { "inline": "_value/1024/1024" } },
       "type": "sum"
      }
     ],
     "query": "event:\"transfer.inv.local.single\" AND source_url:\"*casa-dtn*\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Stage_OUT",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "bytes_transferred",
       "id": "1",
       "inlineScript": "_value/1024/1024",
       "meta": {},
       "settings": { "script": { "inline": "_value/1024/1024" } },
       "type": "sum"
      }
     ],
     "query": "event:\"transfer.inv.local.single\" AND destination_url:\"*casa-dtn*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Files Transferred over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Files Transferred" }
   ],
   "targets": [
    {
     "alias": "Stage_IN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "total_files",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "event:\"transfer.inv.local.single\" AND source_url:\"*casa-dtn*\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Stage_OUT",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "event:\"transfer.inv.local.single\" AND destination_url:\"*casa-dtn*\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}